version: "3.9"

services:
  backend-blue:
    image: ls-backend:latest
    container_name: backend-blue
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
    networks:
      - my-network
    profiles:
      - blue

  backend-green:
    image: ls-backend:latest
    container_name: backend-green
    ports:
      - "8001:8001"
    environment:
      - TZ=Asia/Seoul
    networks:
      - my-network
    profiles:
      - green

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

networks:
  my-network:
    external: true