version: "3.9"

services:
  backend:
    image: ls-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

networks:
  my-network:
    external: true