global:
  scrape_interval: 10s # 10초 마다 Metric을 Pulling
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'backend'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['backend-blue:8000', 'backend-green:8001']