spring:
  application:
    name: log-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: lightswitch

#logging
logging:
  file:
    name: "./log-service.log"
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    com:
      lightswitch:
        logservice: DEBUG
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG
          security: DEBUG