spring:
  datasource:
    url: jdbc:postgresql://15.165.127.196:5432/testdb
    username: testuser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: 15.165.127.196