server:
  port: 8000

spring:
  application:
    name: core-service
  profiles:
    active: dev
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lightswitch2024@gmail.com
    password: vqzwtrcffaseolyt
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: k10s202.p.ssafy.io
      port: 6379
      password: switchlight2024!
      code:
        signup: signup-authentication-code

#actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus
