spring:
  application:
    name: core-service
  profiles:
    active: dev
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lightswitch2024@gmail.com
    password: vqzwtrcffaseolyt
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#            required: true
#
#          timeout: 20000
#          connection-timeout: 20000
#          writetimeout: 20000
  data:
    redis:
      host: k10s202.p.ssafy.io
      port: 6379
      password: switchlight2024!

#logging
logging:
  file:
    name: "./core-service.log"
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    com:
      lightswitch:
        core: DEBUG
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG
          security: DEBUG